name: flutter_map_tappable_polyline
description: A flutter_map plugin that adds Polyline class with onTap event
version: 2.0.0
homepage: https://github.com/OwnWeb/flutter_map_tappable_polyline

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_map: ^0.13.1
  latlong2: ^0.8.0

dev_dependencies:
  pedantic: ^1.9.2
